### ISSUE TITLE
Error in production, not dev

### ISSUE THREAD

**Issue by jxxcarlson** [akappen/s3_direct_upload#3]
Hello,

I get the error below in "production" where the  Phoenix server is on Heroku.  When I run everything locally on my laptop, there is no error.

```
Server: nshost.herokuapp.com:80 (http)
2018-03-30T03:30:09.171248+00:00 app[web.1]: Request: GET /api/credentials?filename=geometric.jpeg&mimetype=image/jpeg&bucket=noteimages
2018-03-30T03:30:09.171250+00:00 app[web.1]: ** (exit) an exception was raised:
2018-03-30T03:30:09.171252+00:00 app[web.1]:     ** (UndefinedFunctionError) function Date.to_iso8601/2 is undefined or private. Did you mean one of:
2018-03-30T03:30:09.171254+00:00 app[web.1]:
2018-03-30T03:30:09.171257+00:00 app[web.1]:       * to_iso8601/1
2018-03-30T03:30:09.171258+00:00 app[web.1]:
2018-03-30T03:30:09.171260+00:00 app[web.1]:         (elixir) Date.to_iso8601(~D[2018-03-30], :basic)
2018-03-30T03:30:09.171262+00:00 app[web.1]:         (s3_direct_upload) lib/s3_direct_upload.ex:137: S3DirectUpload.credential/0
2018-03-30T03:30:09.171264+00:00 app[web.1]:         (s3_direct_upload) lib/s3_direct_upload.ex:129: S3DirectUpload.conditions/1
2018-03-30T03:30:09.171266+00:00 app[web.1]:         (s3_direct_upload) lib/s3_direct_upload.ex:118: S3DirectUpload.policy/1
2018-03-30T03:30:09.171268+00:00 app[web.1]:         (s3_direct_upload) lib/s3_direct_upload.ex:77: S3DirectUpload.presigned/1
2018-03-30T03:30:09.171274+00:00 app[web.1]:         (koko_web) lib/koko_web/controllers/credentials_controller.ex:25: Koko.Web.CredentialsController.send_credentials/1
2018-03-30T03:30:09.171292+00:00 app[web.1]:         (koko_web) lib/koko_web/controllers/credentials_controller.ex:1: Koko.Web.CredentialsController.action/2
2018-03-30T03:30:09.171296+00:00 app[web.1]:         (koko_web) lib/koko_web/controllers/credentials_controller.ex:1: Koko.Web.CredentialsController.phoenix_controller_pi
```

**Comment by jxxcarlson** [comment]
Fixed: I was using an older version of Elixir on Heroku.
